### PR TITLE
Added NASA using JSON Schema

### PR DESCRIPTION
**Pull request by Era-cell**
If we can have two links, github also can be mentioned. If one has to chosen. I am not sure to choose between notice in nasa's website or github.

### CODE REVIEW

**Comment by jviotti** [comment]
The `README` file is auto-generated. Please add the links to https://github.com/sourcemeta/awesome-jsonschema/blob/master/data.yaml and run `npm start`. See https://github.com/sourcemeta/awesome-jsonschema/blob/master/CONTRIBUTING.md

**Comment by Era-cell** [comment]
> The `README` file is auto-generated. Please add the links to https://github.com/sourcemeta/awesome-jsonschema/blob/master/data.yaml and run `npm start`. See https://github.com/sourcemeta/awesome-jsonschema/blob/master/CONTRIBUTING.md

@jviotti should it go under adaption. They are using it in their github too and they even have documentation on it.

**Comment by jviotti** [comment]
Yes, it should go under adoption. You can put the main link

**Comment by jviotti** [comment]
Note that you don't need to close and re-open PRs to make changes. You can make them in place

**Comment by Era-cell** [comment]
I removed my latest commit and pushed in into remote. The PR which was open got closed. Reverting of the commit caused this

**Pull request closed without merging**
